### ISSUE TITLE
Increment reference value when duplicating components

### ISSUE THREAD

**Issue by benjiao** [ohmify/Circuit-Canvas-Issues#10]
Right now, I have to update the reference number whenever I duplicate a component. It would be very helpful and less prone to error if it does it automatically.

[Screencast from 2024-08-13 22-38-24.webm](https://github.com/user-attachments/assets/a2e8bb6f-773d-4627-9ccc-bab7749a1803)

**Comment by ohmify** [comment]
Fixed!
