### ISSUE TITLE
Add a way to move objects front or back in the Layout view

### ISSUE THREAD

**Issue by benjiao** [ohmify/Circuit-Canvas-Issues#13]
Right now, this can be remedied by moving an object side-to-side, but it can be difficult to do when a big object covers a smaller one. 

[Screencast from 2024-08-15 15-40-39.webm](https://github.com/user-attachments/assets/f1e083cf-e917-494b-8067-e1eac2680ff8)

**Comment by ohmify** [comment]
@benjiao I've added the option of sending to back or bringing to front by selecting, then using Ctrl-8 or Ctrl-9. These are just temporary shortcuts. Not sure what shortcuts would make the most sense. Do you have any suggestions?

**Comment by benjiao** [comment]
Cool! I often see it as `Ctrl+[` (backward) and `Ctrl+]` (forward)

**Comment by benjiao** [comment]
`Ctrl + Numbers` apparently has conflicts with chrome shortcuts

![Screenshot from 2024-09-30 04-35-57](https://github.com/user-attachments/assets/08b853cb-2dfd-449b-a5ad-caf998d0c334)

**Comment by ohmify** [comment]
@benjiao Thanks! On norwegian key layout, the keys [ and ] don't exist, so on my laptop that doesn't work. But I've added that key combination now, plus Page Up and Page Down as an alternative for use Norwegians and other countries that might have the same problem.

Can you test before I close the issue?

**Comment by benjiao** [comment]
@ohmify I see. That's interesting. 

Tested it and both [  ] and Page Up/Page Down options work great from my end.
