### ISSUE TITLE
Raspberry Pi Pico Layout Component is Wrong

### ISSUE THREAD

**Issue by JonathanJol** [ohmify/Circuit-Canvas-Issues#14]
The numbers and names of the right side of the components are not referenced correctly. 

![pico-pinout](https://github.com/user-attachments/assets/2be9809b-1e2a-4843-abc6-0dd1dfdab773)

![image](https://github.com/user-attachments/assets/5b23c57e-f4a4-4e04-8a80-073d076227a7)

**Comment by ohmify** [comment]
It was just the numbers that were in the opposite direction, right? I've fixed this:

![image](https://github.com/user-attachments/assets/ca016c01-f5b0-4afb-8ad8-2f6f02f67b3a)
