### ISSUE TITLE
Customizable font sizes

### ISSUE THREAD

**Issue by benjiao** [ohmify/Circuit-Canvas-Issues#8]
I'm using the text feature to add some pin numbers and I'd like to make them a bit smaller.

![Screenshot from 2024-08-13 22-16-56](https://github.com/user-attachments/assets/49bbd02f-bde5-4d7b-ae44-2f08aa2fa4ff)

**Comment by ohmify** [comment]
Fixed this. Double-click to change the text and/or the size
